Update gcp.md
when using the file as is got the following error (excact file location dropped for security reason):
ERROR: (gcloud.iam.roles.create) Failed to parse YAML from .... in "aqua-security-audit-role.yaml", line 3, column 24

This change in line 3 fixed the issue